### PR TITLE
Update RustCrypto deps

### PR DESCRIPTION
**Pull request by yotamofek**
First of all,
thanks for this awesome library!

This PR updates updates all outdated dependencies, and fixes the code to comply with all the breaking changes from here: https://www.reddit.com/r/rust/comments/h0em5n/ann_new_rustcrypto_releases_aead_blockcipher/ (100% of the changes are semantic renaming of functions).
Also fixed a few clippy warnings for good measure.

### CODE REVIEW

**Comment by yotamofek** [comment]
@mikkyang any chance you could have a look at this? :) Thanks!

**Comment by mikkyang** [comment]
Thanks for the contribution!

**Comment by mikkyang** [comment]
Released in https://github.com/mikkyang/rust-jwt/releases/tag/0.8.0

**Comment by yotamofek** [comment]
Thank you for this library :)

**Pull request merged**
